### here we go -> create Teams

POST http://localhost:8000/
Content-Type: application/json

{
  "players": [
    {
      "name": "Ömer"
    },
    {
      "name": "Büny"
    },
    {
      "name": "Enes"
    },
    {
      "name": "Sinan"
    },
    {
      "name": "Serkan"
    },
    {
      "name": "Ali"
    },
    {
      "name": "Mustafa"
    },
    {
      "name": "Fatih"
    },
    {
      "name": "Yusuf"
    },
    {
      "name": "Ibrahim Abi"
    }
  ]
}