Insert Into Player (id, name, skill, numOfWins) VALUES (1, 'Ömer', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (2, 'Abraham', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (3, 'Cihan', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (4, 'Enes', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (5, 'Serkan', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (6, 'Cihan', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (7, 'Yusuf', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (8, 'Büny', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (9, 'Ali', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (10, 'Muhammed', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (11, 'Sinan', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (12, 'Koray', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (13, 'Mustafa', 8.0, 0);
Insert Into Player (id, name, skill, numOfWins) VALUES (14, 'Furkan AK', 8.0, 0);